---
title: "heritSeq miRNA analysis (Pratyay Rudra)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
########### Final analysis of our miRNA expression data using heritseq ############

install.packages("HeritSeq")
source("https://bioconductor.org/biocLite.R")
biocLite("DESeq2")
biocLite("SummarizedExperiment")
install.packages("R2admb")
install.packages("glmmADMB", 
                 repos=c("http://glmmadmb.r-forge.r-project.org/repos",
                         getOption("repos")),
                 type="source")

library("HeritSeq")
library("glmmADMB")

load("mirna.data.RObj")



##### VPC #####
LXSmiRNA <- mirna.nb.adj
LXSstrains <- strains
cds <- DESeqDataSetFromMatrix(countData = round(LXSmiRNA), 
                              colData = data.frame(strain = strains),
                              design = ~ strain)
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds, fitType = "local")
vsd <- DESeq2::varianceStabilizingTransformation(cds, fitType = "local")
miRNA.vst <- assay(vsd)
result.vst <- fitComputeVPC.lmer(miRNA.vst, strains, test = TRUE)
vpc.vst <- result.vst[[1]]
pval.vst <- result.vst[[2]]


##### NB ######
result.nb <- fit.NB(round(mirna.nb.adj), strains, test = T)
para.nb <- result.nb[[1]]
pval.nb <- result.nb[[2]]
vpc.nb <- computeVPC.NB(para.nb)


##### CP ######
result.cp <- fit.CP(mirna.nb.adj, strains, test = T)
para.cp <- result.cp[[1]]
pval.cp <- result.cp[[2]]
vpc.cp <- computeVPC.CP(para.cp)

save(result.cp, result.nb, pval.cp, vpc.cp, pval.nb, vpc.nb, pval.vst, vpc.vst, 
     file = "analysis.done.Robj")

```


```{r,final}
load("analysis.done.Robj")


```