#######################################
# TITLE: Phenotype Analysis Functions
# AUTHOR: Gordon Kordas
# DATE: 03/01/2019
#######################################

#=================================#
# FUNCTION: calculate correlation
# between phenotype and miRNA expr
#=================================#

phenotype_corrs <- function(pheno_df,mirna_expr){
  # remove missing strains #
  colnames(pheno_df) <- "pheno"
  pheno_df <- pheno_df[complete.cases(pheno_df),,drop = FALSE]
  
  # check common strains #
  common <- intersect(row.names(pheno_df),colnames(mirna_expr))
  mirna_pheno <- mirna_expr[,common] #881 x 59
  overlap_pheno <- pheno_df[common,] #length 59 vector
  names(overlap_pheno) <- common
  
  phenomircor <- numeric(nrow(mirna_pheno))
  
  # compute the correlations between mirna and phenotype #
  for (i in 1:nrow(mirna_pheno)){
    phenomircor[i] <- cor.test(overlap_pheno,as.numeric(mirna_pheno[i,]))$p.value
  }
  
  phenomirsp <- numeric(nrow(mirna_pheno))
  
  # compute spearman correlations #
  for (i in 1:nrow(mirna_pheno)){
    phenomirsp[i] <- cor.test(overlap_pheno,as.numeric(mirna_pheno[i,]),method = "spearman",exact = FALSE)$p.value
  }
  
  # calculate FDR values #
  phenomir_q <- p.adjust(phenomircor, method = "BH")
  phenomir_q_sp <- p.adjust(phenomirsp, method = "BH")
  
  # return overlap and q values #
  out <- data.frame(rownames(mirna_pheno),phenomir_q,phenomir_q_sp)
  names(out) <- c("mirna_overlap","corr_fdr","spear_corr_fdr")
  return(out)
}


#=================================#
# FUNCTION: perform QTL analysis
# between phenotype and sdps
#=================================#

phenotype_qtl <- function(pheno_df,sdps){
  
  # remove missing strains #
  colnames(pheno_df) <- "pheno"
  pheno_df <- pheno_df[complete.cases(pheno_df),,drop = FALSE]
  
  # iterate over all sdps of interest #
  lm_mat <- matrix(nrow = nrow(sdps),ncol = 2) # one col for T, one for p-val
  
  for (ii in 1:nrow(sdps)){
    
    # check common strains #
    common <- intersect(row.names(pheno_df),colnames(sdps))
    sdp_pheno <- sdps[ii,common] #881 x 59
    overlap_pheno <- pheno_df[common,] #length 59 vector
    names(overlap_pheno) <- common
    
    # perform linear regression #
    lm_obj <- summary(lm(as.numeric(overlap_pheno) ~ as.numeric(sdp_pheno)))
    lm_mat[ii,] <- c(coef(lm_obj)[2,3],coef(lm_obj)[2,4])
  }
  
  # add sdp names and colnames #
  rownames(lm_mat) <- rownames(sdps)
  colnames(lm_mat) <- c("tstat","pval")
  return(lm_mat)
}


#================================# 
# FUNCTION: return significant 
# qtl associations from list 
# generated by phenotype_qtl()
#================================#

pheno_sig <- function(pheno_qtl){
  pheno_qtl <- as.data.frame(pheno_qtl)
  pheno_qtl$sdp <- rownames(pheno_qtl)
  return(pheno_qtl %>% dplyr::filter(pval < 0.05))
}







